Section "InputClass"
    Identifier      "calibration"
    MatchProduct    "ADS7846 Touchscreen"
    Driver          "libinput"
    Option          "CalibrationMatrix" "0 -1.1349 1.0839 1.0748 0 -0.0394 0 0 1"
EndSection
