# Drop-in replacement for /etc/bluetooth/main.conf
# Only the sections/keys we override are shown. Leaving others at default is fine.

[General]
Class = 0x200414
DiscoverableTimeout = 0
ControllerMode = bredr

[Policy]
AutoEnable=true
